### PR TITLE
Added winget submission

### PR DESCRIPTION
**Pull request by gnpaone**
@rcmaehl Once check this out for #28

### CODE REVIEW

**Comment by Macleykun** [comment]
https://github.com/rcmaehl/MSEdgeRedirect/blob/main/.github/workflows/winget-submission.yml
🤔 ?
if you like to refactor the winget update submission, perhaps it's best to remove the old one... if your certain xD ?
Bit confused why this PR is created, you want to add choco support instead maybe?

**Comment by gnpaone** [comment]
> https://github.com/rcmaehl/MSEdgeRedirect/blob/main/.github/workflows/winget-submission.yml 🤔 ? if you like to refactor the winget update submission, perhaps it's best to remove the old one... if your certain xD ? Bit confused why this PR is created, you want to add choco support instead maybe?

Yah, that's what I first thought too, I mean removing multiple workflows and integrate into single workflow so I created #81 but in https://github.com/rcmaehl/MSEdgeRedirect/issues/28#issuecomment-1043972731 he mentioned that it's good if it's in seperate workflow rather than single workflow and I felt that too so again modified in #82

**Comment by Macleykun** [comment]
Mmm ok.. but why didn’t you add the changes all in one PR..? I’m a bit confused, I’ll just assume ya know what your doing

**Comment by gnpaone** [comment]
> Mmm ok.. but why didn’t you add the changes all in one PR..? I’m a bit confused, I’ll just assume ya know what your doing 

Actually I am not sure if @rcmaehl is ok with multiple workflows or single workflow, #81 is single workflow and #82 is multiple workflow, so either one of them will be closed based on that, apart from that both PRs contain same code changes. If I had added both kinds of changes in same PR I thought it would not be correct. Sorry for the inconvenience.

**Comment by Macleykun** [comment]
> > Mmm ok.. but why didn’t you add the changes all in one PR..? I’m a bit confused, I’ll just assume ya know what your doing
> 
> Actually I am not sure if @rcmaehl is ok with multiple workflows or single workflow, #81 is single workflow and #82 is multiple workflow, so either one of them will be closed based on that, apart from that both PRs contain same code changes. If I had added both kinds of changes in same PR I thought it would not be correct. Sorry for the inconvenience.

I think he doesn’t mind how it’s setup, the most important part is that you know it works 100%.

**Comment by gnpaone** [comment]
> > > Mmm ok.. but why didn’t you add the changes all in one PR..? I’m a bit confused, I’ll just assume ya know what your doing
> > 
> > Actually I am not sure if @rcmaehl is ok with multiple workflows or single workflow, #81 is single workflow and #82 is multiple workflow, so either one of them will be closed based on that, apart from that both PRs contain same code changes. If I had added both kinds of changes in same PR I thought it would not be correct. Sorry for the inconvenience.
> 
> I think he doesn’t mind how it’s setup, the most important part is that you know it works 100%.

Yeah absolutely, it works 💯☺️.

**Pull request closed without merging**
