### PR TITLE
Modified winget submission

### PR DESCRIPTION
**Pull request by gnpaone**
Once check this too for #28 @rcmaehl

### CODE REVIEW

**Comment by Macleykun** [comment]
…why didn’t you do this within the same PR?

**Comment by gnpaone** [comment]
> …why didn’t you do this within the same PR?

Actually I am not sure if @rcmaehl is ok with multiple workflows or single workflow, #81 is single workflow and #82 is multiple workflow, so either one of them will be closed based on that, apart from that both PRs contain same code changes. If I had added both kinds of changes in same PR I thought it would not be correct. Sorry for the inconvenience.

**Comment by gnpaone** [comment]
https://github.com/gnpaone/MSEdgeRedirect/blob/4b8439e9bd93e518e9da02f3d13f1ef26d0b6c3b/.github/workflows/winget-submission.yml#L22 line change auto-assigns the architecture in winget manifests similar to https://github.com/rcmaehl/MSEdgeRedirect/blob/221b82d24c8f09529b8e111a3ee4cb49ee772df0/.github/workflows/MSER.yml#L33 used by @rcmaehl in his https://github.com/rcmaehl/MSEdgeRedirect/blob/main/.github/workflows/MSER.yml workflow.

**Comment by Macleykun** [comment]
Shouldn’t mine winget workflow be removed..?

**Comment by gnpaone** [comment]
> Shouldn’t mine winget workflow be removed..?

No not really, editing your workflow with word changes made in my workflow will do the job or else replacing the workflow will do the same.

**Comment by Macleykun** [comment]
> > Shouldn’t mine winget workflow be removed..?
> 
> No not really, editing your workflow with word changes made in my workflow will do the job or else replacing the workflow will do the same.

So it wouldn’t make a double winget submission then?

**Comment by gnpaone** [comment]
> > > Shouldn’t mine winget workflow be removed..?
> > 
> > No not really, editing your workflow with word changes made in my workflow will do the job or else replacing the workflow will do the same.
> 
> So it wouldn’t make a double winget submission then?

No it wouldn't, it's just the same workflow, not different, just that GitHub tends to run the workflow after changes, probably skip the run from actions. Also shall I remove the job completion immediately after first workflow thing in the workflow and just keep the running workflow only after release?

**Comment by Macleykun** [comment]
> > > > Shouldn’t mine winget workflow be removed..?
> > > 
> > > 
> > > No not really, editing your workflow with word changes made in my workflow will do the job or else replacing the workflow will do the same.
> > 
> > 
> > So it wouldn’t make a double winget submission then?
> 
> No it wouldn't, it's just the same workflow, not different, just that GitHub tends to run the workflow after changes, probably skip the run from actions. Also shall I remove the job completion immediately after first workflow thing in the workflow and just keep the running workflow only after release thing?

Eh.. don’t get what your saying here but if your certain this work create a double submission then it’s all ok for me

**Comment by gnpaone** [comment]
> > > > > Shouldn’t mine winget workflow be removed..?
> > > > 
> > > > 
> > > > No not really, editing your workflow with word changes made in my workflow will do the job or else replacing the workflow will do the same.
> > > 
> > > 
> > > So it wouldn’t make a double winget submission then?
> > 
> > No it wouldn't, it's just the same workflow, not different, just that GitHub tends to run the workflow after changes, probably skip the run from actions. Also shall I remove the job completion immediately after first workflow thing in the workflow and just keep the running workflow only after release thing?
> 
> Eh.. don’t get what your saying here but if your certain this work create a double submission then it’s all ok for me

I meant can I remove the green highlighted part in the pic?

**Comment by gnpaone** [comment]
Done, now it's good

> > Eh.. don’t get what your saying here but if your certain this work create a double submission then it’s all ok for me
> 
> I meant can I remove the green highlighted part in the pic?

**Review by gnpaone — COMMENTED** [review]
Now it's good to merge I guess

**Pull request merged**
