### PR TITLE
WIP Add winget (and possibly also choco) support

### PR DESCRIPTION
**Pull request by Macleykun**
Winget/Choco make it very easy to install programs on windows, this also shall (partly) solve #28

### CODE REVIEW

**Comment by Macleykun** [comment]
I followed these steps: 
https://github.com/TechWatching/winget-package-submission

I believe the logic is right, but that i'm simply not understanding how to correctly push tags with a commit in one go.
The only steps that have to be done are:
generate a PAT with the scope public_repo and add it to the secrets of your project with the name Project_PAT

I do suggest to test out for yourself.

**Comment by Macleykun** [comment]
After it's well tested that winget works, i'll look with choco :)
i'm sorry for not being able to test this out myself properly.

**Comment by rcmaehl** [comment]
@Macleykun Is this okay to merge. Everything looks okay as far as I can tell

**Review by rcmaehl — APPROVED** [review]

**Comment by Macleykun** [comment]
> @Macleykun Is this okay to merge. Everything looks okay as far as I can tell

Yes

**Comment by Macleykun** [comment]
Awsome! Please let me know how the first official test went!

**Pull request merged**
